// Generated by gencpp from file ros_service_examples/MP3InventoryServiceRequest.msg
// DO NOT EDIT!


#ifndef ROS_SERVICE_EXAMPLES_MESSAGE_MP3INVENTORYSERVICEREQUEST_H
#define ROS_SERVICE_EXAMPLES_MESSAGE_MP3INVENTORYSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_service_examples
{
template <class ContainerAllocator>
struct MP3InventoryServiceRequest_
{
  typedef MP3InventoryServiceRequest_<ContainerAllocator> Type;

  MP3InventoryServiceRequest_()
    : request_string()
    , album()  {
    }
  MP3InventoryServiceRequest_(const ContainerAllocator& _alloc)
    : request_string(_alloc)
    , album(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _request_string_type;
  _request_string_type request_string;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _album_type;
  _album_type album;




  typedef boost::shared_ptr< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MP3InventoryServiceRequest_

typedef ::ros_service_examples::MP3InventoryServiceRequest_<std::allocator<void> > MP3InventoryServiceRequest;

typedef boost::shared_ptr< ::ros_service_examples::MP3InventoryServiceRequest > MP3InventoryServiceRequestPtr;
typedef boost::shared_ptr< ::ros_service_examples::MP3InventoryServiceRequest const> MP3InventoryServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_service_examples

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87eaf88ba36e173ed9b494bb014cce04";
  }

  static const char* value(const ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87eaf88ba36e173eULL;
  static const uint64_t static_value2 = 0xd9b494bb014cce04ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_service_examples/MP3InventoryServiceRequest";
  }

  static const char* value(const ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request_string\n\
string album\n\
";
  }

  static const char* value(const ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_string);
      stream.next(m.album);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MP3InventoryServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_service_examples::MP3InventoryServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "request_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.request_string);
    s << indent << "album: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.album);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SERVICE_EXAMPLES_MESSAGE_MP3INVENTORYSERVICEREQUEST_H
