// Generated by gencpp from file beginner_tutorials/TalkerService.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TALKERSERVICE_H
#define BEGINNER_TUTORIALS_MESSAGE_TALKERSERVICE_H

#include <ros/service_traits.h>


#include <beginner_tutorials/TalkerServiceRequest.h>
#include <beginner_tutorials/TalkerServiceResponse.h>


namespace beginner_tutorials
{

struct TalkerService
{

typedef TalkerServiceRequest Request;
typedef TalkerServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TalkerService
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::TalkerService > {
  static const char* value()
  {
    return "64dad4fb06c88ba65b4fbe95d74ff54b";
  }

  static const char* value(const ::beginner_tutorials::TalkerService&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::TalkerService > {
  static const char* value()
  {
    return "beginner_tutorials/TalkerService";
  }

  static const char* value(const ::beginner_tutorials::TalkerService&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::TalkerServiceRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::TalkerService > 
template<>
struct MD5Sum< ::beginner_tutorials::TalkerServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::TalkerService >::value();
  }
  static const char* value(const ::beginner_tutorials::TalkerServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::TalkerServiceRequest> should match 
// service_traits::DataType< ::beginner_tutorials::TalkerService > 
template<>
struct DataType< ::beginner_tutorials::TalkerServiceRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::TalkerService >::value();
  }
  static const char* value(const ::beginner_tutorials::TalkerServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::TalkerServiceResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::TalkerService > 
template<>
struct MD5Sum< ::beginner_tutorials::TalkerServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::TalkerService >::value();
  }
  static const char* value(const ::beginner_tutorials::TalkerServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::TalkerServiceResponse> should match 
// service_traits::DataType< ::beginner_tutorials::TalkerService > 
template<>
struct DataType< ::beginner_tutorials::TalkerServiceResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::TalkerService >::value();
  }
  static const char* value(const ::beginner_tutorials::TalkerServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TALKERSERVICE_H
