(cl:defpackage ros_service_examples-srv
  (:use )
  (:export
   "MP3INVENTORYSERVICE"
   "<MP3INVENTORYSERVICE-REQUEST>"
   "MP3INVENTORYSERVICE-REQUEST"
   "<MP3INVENTORYSERVICE-RESPONSE>"
   "MP3INVENTORYSERVICE-RESPONSE"
  ))

